// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dae45575-77c0-4390-bacb-3da2c5e60365",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TmMDNFy2A",
    "aws_user_pools_web_client_id": "3m3p1gpneah664gfk2fnaf10se",
    "oauth": {},
    "aws_content_delivery_bucket": "popcorn-style-2-20190713125339-hostingbucket-popcorn",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://popcorn-style-2-20190713125339-hostingbucket-popcorn.s3-website-us-east-1.amazonaws.com",
    "aws_user_files_s3_bucket": "popcorn-style-2ffbf2d92a9dc46e9ac27c30a37771b3b-popcorn",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
